inherit_gem:
  rubocop-inst:
  - rubocop.yml
  - rubocop-rspec.yml

plugins:
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2

Bundler/DuplicatedGem:
  Enabled: false

Naming/FileName:
  Exclude:
    - lib/nokogiri-xmlsec.rb

RSpec/NamedSubject:
  Enabled: false

Style/Documentation:
  Enabled: false
